COLUMN PROGRAM FORMAT A40
COLUMN START_TIME FORMAT A20
COLUMN USER FORMAT A10
SET LINES 120
SELECT * FROM (
SELECT NAM.USER_CONCURRENT_PROGRAM_NAME PROGRAM, CON.REQUEST_ID REQUEST_ID, 
CON.ACTUAL_START_DATE START_TIME, 
TRUNC( (SYSDATE-CON.ACTUAL_START_DATE)*1440,2) TIME_MIN,
CON.STATUS_CODE STATUS, US.USER_NAME "USER"
FROM FND_CONCURRENT_PROGRAMS_TL NAM, FND_CONCURRENT_REQUESTS CON, FND_USER US
WHERE CON.CONCURRENT_PROGRAM_ID=NAM.CONCURRENT_PROGRAM_ID
AND CON.REQUESTED_BY = US.USER_ID
AND CON.PHASE_CODE='R')
WHERE TIME_MIN > 15;
