SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM DBA_OBJECTS
WHERE STATUS !='VALID';

COLUMN OBJECT_NAME FORMAT A30
SET LINES 1200
SET PAGES 200
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM DBA_OBJECTS
WHERE STATUS !='VALID'
AND OBJECT_TYPE = 'PACKAGE BODY';
